global:
  scrape_interval: 1s
  evaluation_interval: 1s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: py
    static_configs:
    - targets:
      - localhost:8000